### ISSUE TITLE
Received error on running Huggingface LLM on a Windows 10 machine

### ISSUE THREAD

**Issue by stevevaius2015** [namuan/dr-doc-search#15]
After installing your library and tried given example on my win10 machine I got following error
`Invalid Parameter - 150
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\dr-doc-search.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\doc_search\app.py", line 68, in main
    run_workflow(context, training_workflow_steps())
  File "C:\Python310\lib\site-packages\py_executable_checklist\workflow.py", line 36, in run_workflow
    __run_step(step, context)
  File "C:\Python310\lib\site-packages\py_executable_checklist\workflow.py", line 29, in __run_step
    returned_context = step_instance.execute() or {}
  File "C:\Python310\lib\site-packages\doc_search\workflow\__init__.py", line 120, in execute
    run_command(convert_command)
  File "C:\Python310\lib\site-packages\py_executable_checklist\workflow.py", line 9, in run_command
    return subprocess.check_output(command, shell=True).decode("utf-8")  # nosemgrep
  File "C:\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'convert -density 150 -trim -background white -alpha remove -quality 100 -sharpen 0x1.0 C:\Users\XXXX\OutputDir\dr-doc-search\parable_monetary_economy\parable_monetary_economy.pdf[1] -quality 100 C:\Users\XXXX\OutputDir\dr-doc-search\parable_monetary_economy\images\output-1.png' returned non-zero exit status 4.`

Any Help to fix this issue?

**Comment by namuan** [comment]
This is probably related to #7

**Comment by namuan** [comment]
This is merged and available in `1.6.3`. You'll need to set up an environment variable with the location of ImageMagick executable file before running this. See the README for more info

![image](https://user-images.githubusercontent.com/575441/219901375-9466e773-7964-4de3-aa6b-5be489681a1c.png)
